#!/bin/sh
#
# PROVIDE: sample
# REQUIRE: networking
# KEYWORD:

. /etc/rc.subr

name="sample"
rcvar="sample_enable"
sample_user="sample"
sample_command="/usr/local/sample/sample"
pidfile="/var/run/sample/${name}.pid"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -r -f ${sample_command}"

load_rc_config $name
: ${sample_enable:=no}

run_rc_command "$1"
